### PR TITLE
added WASD support and Harambe.

### PR DESCRIPTION
**Pull request by agrimrules**
Hey Sid cool project.
I made some minor contributions by adding in Harambe as a reason and also support for WASD controls for some typical PC gaming. moving forward I would make a few suggestions.

- You seem to be doing a lot of Python lately. there were no semi-colons anywhere 😛 

- You should probably move all the script out side of `index.html` and create like a `musk2mars.js`

- Also minify the newly created `musk2mars.js` to prevent people from cheating in the game 😸 

Good job tough! 👍

### CODE REVIEW

**Comment by agrimrules** [comment]
Also you have been signing your commits with your work email :trollface: .

**Comment by sidthekidder** [comment]
Thanks for the PR agrim! Yes I'm a fan of the no-semicolons in JS style, also that second email account/ SSH key annoys me a lot, have to fix it someday!

**Comment by sidthekidder** [comment]
Did you use TexturePacker or what for adding the png image? And how did you know it was a work email? 😛

**Comment by agrimrules** [comment]
`git log` showed me that you used a different email. If I am on my work machine the first think I do is change `git config user.email` when I clone a repo. There is still a way to change it for all previous commits if you look around. Also I used photoshop for editing the sprites. As soon as I saved the file Pixi wasn't picking it up. Then I realized that they have to be in 32-bit color PNG for Pixi to render them.

**Pull request merged**
